version: '3.8'

services:
  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: selenium-test-runner
    volumes:
      - ./tests:/tests
    depends_on:
      web:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - devops-net

  web:
    build:
      context: .
    container_name: web-app
    ports:
      - "5173:5173"
    networks:
      - devops-net
    command: ["npm", "run", "dev"]
    environment:
      - VITE_API_URL=http://backend:2000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "2000:2000"
    networks:
      - devops-net
    command: ["npm", "run", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/health"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  devops-net:
    driver: bridge
